/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package AbstractContext;

import AbstractContext.Service.GoingHome;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;

public class App {

    public static void main(String[] args) {
        var context =
                new AnnotationConfigApplicationContext(ConfigurationBeans.class);
        GoingHome goingHome = context.getBean(GoingHome.class);
        goingHome.getMsgUsingCar();
        System.out.println("Speed "+goingHome.getSpeedUsingCar());
        System.out.println("Speed using Plan "+ goingHome.getSpeedUsingPlan());
        goingHome.getMsgUsingPlan();
    }
}
